// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_cFWxhsbF9TwgBW8cYpdJhQuFDB0t1Y',
    appId: '1:817995314374:android:2f763db07d3867951d53c7',
    messagingSenderId: '817995314374',
    projectId: 'tarotcelestialapp',
    storageBucket: 'tarotcelestialapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM41D1OO_qsqHGN3LVlBDzSAL4qEWzGlA',
    appId: '1:817995314374:ios:83f103285a5bfd8b1d53c7',
    messagingSenderId: '817995314374',
    projectId: 'tarotcelestialapp',
    storageBucket: 'tarotcelestialapp.appspot.com',
    androidClientId: '817995314374-otl52g7a6jv5os2i139ac00ig6bvk4qs.apps.googleusercontent.com',
    iosClientId: '817995314374-0vdrtpok4k7he5o8p09gm93al63nci0o.apps.googleusercontent.com',
    iosBundleId: 'com.tarotcelestial.app',
  );
}
